Cast SortMethod to enum
Downloading from meter would return a GXEnum object instead of the expected SortMethod.

```
Traceback (most recent call last):
  ...
  File "/nix/store/cjkcj4zvpka3c8b1bhj94v7pcp6skrbi-python3-3.7.6-env/lib/python3.7/site-packages/gurux_dlms/objects/GXDLMSProfileGeneric.py", line 348, in getValue
    ret = self.sortMethod.value
AttributeError: 'GXEnum' object has no attribute 'value'
```