Fix `TypeError` in `GXDLMS`
handleMethodResponse was passing on `GXReplyData` instead of `GXByteBuffer` causing a `TypeError`

Fix use of `reply.data` instead of just `reply`.

```
....
  File "./venv/lib/python3.7/site-packages/gurux_dlms/GXDLMS.py", line 1198, in handleMethodResponse
    cls.getDataFromBlock(data, 0)
  File "./venv/lib/python3.7/site-packages/gurux_dlms/GXDLMS.py", line 1857, in getDataFromBlock
    if len(data) == data.position:
TypeError: object of type 'GXReplyData' has no len()
```